function outputs = run_burgers_fem_example()
%RUN_BURGERS_FEM_EXAMPLE One-sample Burgers FEM reproduction example.
%
%   cd examples/burgers_fem_single_sample
%   run_burgers_fem_example
%
% Solves Test 001 with the FNO-seeded and target-seeded AFEM meshes and
% writes numerical results to
%   result/fem/burgers/fno/b3000_mse/base/example_1sample/
% and figures to
%   figures/fem/burgers/fno/b3000_mse/base/example_1sample/

cfg = burgers_fem_example_config();
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
run(fullfile(root,'setup.m'));

% setup may have restored the default path; make sure the example config
% function is resolvable regardless of the current folder.
addpath(fileparts(mfilename('fullpath')));

if cfg.maxGeneration < ceil(12*cfg.scoreMultiplier)
    error('maxGeneration must be at least ceil(12*scoreMultiplier).');
end

validateattributes(cfg.fixedAFEMRefineCycles,{'numeric'}, ...
    {'scalar','real','finite','integer','>=',0});
validateattributes(cfg.afemMaxCycles,{'numeric'}, ...
    {'scalar','real','finite','integer','>=',0});
if cfg.fixedAFEMRefineCycles > cfg.afemMaxCycles
    error(['fixedAFEMRefineCycles=%d exceeds afemMaxCycles=%d. ', ...
           'Increase afemMaxCycles or reduce fixedAFEMRefineCycles.'], ...
        cfg.fixedAFEMRefineCycles,cfg.afemMaxCycles);
end

if isempty(cfg.predictionMat)
    predictionMat = fullfile(root,'result','operators','burgers', ...
        cfg.operatorName,cfg.operatorExperiment,'predictions.mat');
else
    predictionMat = cfg.predictionMat;
end

if isempty(cfg.datasetMat)
    datasetMat = fullfile(root,'data','burgers',sprintf( ...
        'burgers_%d.mat',cfg.datasetCheckpointSamples));
else
    datasetMat = cfg.datasetMat;
end

if isempty(cfg.outputTag)
    tag = sprintf('scale_%03d_threshold_%03d', ...
        round(100*cfg.scoreMultiplier),round(100*cfg.generationThreshold));
else
    tag = cfg.outputTag;
end

baseOverrides = struct( ...
    'predictionMat',predictionMat, ...
    'datasetMat',datasetMat, ...
    'useExactFourierInputs',cfg.useExactFourierInputs, ...
    'exactInputAbsTolerance',cfg.exactInputAbsTolerance, ...
    'exactInputRelTolerance',cfg.exactInputRelTolerance, ...
    'generationThreshold',cfg.generationThreshold, ...
    'numPlotSamples',cfg.numPlotSamples, ...
    'makeMeshPlots',cfg.makeMeshPlots, ...
    'makeScorePlots',cfg.makeScorePlots, ...
    'makePointwisePlots',cfg.makePointwisePlots, ...
    'makeAFEMConvergencePlots',cfg.makeAFEMConvergencePlots, ...
    'saveSampleMeshes',cfg.saveSampleMeshes, ...
    'operatorInitialGrid',cfg.operatorInitialGrid, ...
    'operatorRefinementMultiplier',cfg.scoreMultiplier, ...
    'operatorMaxLevel',cfg.maxGeneration, ...
    'maxElementsCase',cfg.maxElementsCase, ...
    'operatorMaxRefineCalls',cfg.maxRefineCalls, ...
    'fixedAFEMRefineCycles',cfg.fixedAFEMRefineCycles, ...
    'afemMaxCycles',cfg.afemMaxCycles, ...
    'newtonInitializationMode',cfg.newtonInitializationMode, ...
    'runFNOSeededAFEM',cfg.runFNOSeededAFEM, ...
    'runTargetSeededAFEM',cfg.runTargetSeededAFEM, ...
    'runStandardAFEM',cfg.runStandardAFEM, ...
    'runTimeMatchedAFEM',cfg.runTimeMatchedAFEM, ...
    'runAccuracyMatchedAFEM',cfg.runAccuracyMatchedAFEM, ...
    'runFixedRefinementAFEM',cfg.runFixedRefinementAFEM, ...
    'runDOFMatchedUniform',cfg.runDOFMatchedUniform, ...
    'runFixedUniform',cfg.runFixedUniform, ...
    'fixedUniformFreeDOF',cfg.fixedUniformFreeDOF, ...
    'sampleIds',cfg.sampleIds, ...
    'plotSampleIds',cfg.plotSampleIds, ...
    'operatorName',cfg.operatorName);

global NOEM_FEM_RUNTIME_OVERRIDES
cleanup = onCleanup(@() clear_overrides());
outputs = struct();

if cfg.runBase
    NOEM_FEM_RUNTIME_OVERRIDES = baseOverrides;
    NOEM_FEM_RUNTIME_OVERRIDES.hybridAFEMCycles = 0;
    NOEM_FEM_RUNTIME_OVERRIDES.outDir = fullfile(root,'result','fem','burgers', ...
        cfg.operatorName,cfg.operatorExperiment,'base',tag);
    NOEM_FEM_RUNTIME_OVERRIDES.figureDir = fullfile(root,'figures','fem','burgers', ...
        cfg.operatorName,cfg.operatorExperiment,'base',tag);

    outputs.base = burgers_fem_comparison( ...
        cfg.trainSamples,cfg.afemInitialGrid,cfg.numSamples, ...
        cfg.operatorScoreSafetyBias,cfg.operatorExperiment);
end

if cfg.runHybrid
    NOEM_FEM_RUNTIME_OVERRIDES = baseOverrides;
    NOEM_FEM_RUNTIME_OVERRIDES.hybridAFEMCycles = cfg.hybridAFEMCycles;
    NOEM_FEM_RUNTIME_OVERRIDES.outDir = fullfile(root,'result','fem','burgers', ...
        cfg.operatorName,cfg.operatorExperiment,'hybrid',tag);
    NOEM_FEM_RUNTIME_OVERRIDES.figureDir = fullfile(root,'figures','fem','burgers', ...
        cfg.operatorName,cfg.operatorExperiment,'hybrid',tag);

    outputs.hybrid = burgers_fem_comparison( ...
        cfg.trainSamples,cfg.afemInitialGrid,cfg.numSamples, ...
        cfg.operatorScoreSafetyBias,cfg.operatorExperiment);
end
end

function clear_overrides()
global NOEM_FEM_RUNTIME_OVERRIDES
NOEM_FEM_RUNTIME_OVERRIDES = [];
end